name: Build
run-name: "[Build]: ${{ github.event.workflow_run.head_branch }}"

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

concurrency:
  group: build-${{ github.event.workflow_run.head_branch  }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Node.JS
        uses: actions/setup-node@main
        with:
          cache: yarn

      - name: Setup dependencies
        run: yarn

      - name: Build
        run: yarn webpack

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
